// Die wöchentliche Anhebung der Abhängigkeiten (.github/workflows/deps-update.yml).
//
// Entscheidung des Users (24.09.2026, hier übernommen am 26.09.): angehoben
// wird nur, wenn an keiner Plattform etwas angepasst werden muss — und das wird
// VOR dem PR geprüft. Diese Tests halten fest, dass der Ablauf so gebaut bleibt,
// und prüfen die beiden Hilfsskripte an echten Eingaben:
//   - .github/scripts/deps_pr_text.py        (PR-Text bzw. Meldung)
//   - .github/scripts/linux-systembibliotheken.sh
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

final String _wurzel = Directory.current.path;

const String _altLock = '''
# Generated by pub
packages:
  archive:
    dependency: "direct main"
    description:
      name: archive
      sha256: "0000"
      url: "https://pub.dev"
    source: hosted
    version: "4.0.9"
  flutter_webrtc:
    dependency: "direct main"
    description:
      name: flutter_webrtc
      sha256: "0000"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.2+hotfix.2"
  icd_klingel:
    dependency: "direct main"
    description:
      path: "packages/icd_klingel"
      relative: true
    source: path
    version: "1.0.0"
  js:
    dependency: transitive
    description:
      name: js
      sha256: "0000"
      url: "https://pub.dev"
    source: hosted
    version: "0.7.2"
sdks:
  dart: ">=3.6.1 <4.0.0"
''';

String get _neuLock => _altLock
    .replaceFirst('version: "4.0.9"', 'version: "4.3.0"')
    .replaceFirst('version: "1.6.2+hotfix.2"', 'version: "1.6.2+hotfix.3"')
    .replaceFirst(RegExp(r'  js:\n(    .*\n|      .*\n)*'), '');

String _p(String name, String kind, String cur, String res, String lat) =>
    '{"package":"$name","kind":"$kind","isDiscontinued":false,'
    '"replacedBy":null,"isCurrentRetracted":false,'
    '"isCurrentAffectedByAdvisory":false,'
    '"current":{"version":"$cur"},"upgradable":{"version":"$cur"},'
    '"resolvable":{"version":"$res"},"latest":{"version":"$lat"}}';

final String _outdated = '{"packages":[${[
  _p('file_picker', 'direct', '10.3.10', '11.0.3', '11.0.3'),
  _p('qr', 'transitive', '3.0.2', '3.0.2', '4.0.0'),
].join(',')}]}';

const String _deps = '''
{"root":"app","packages":[
 {"name":"app","kind":"root","source":"root","dependencies":["file_picker"]},
 {"name":"barcode","kind":"transitive","source":"hosted","dependencies":["qr"]}
]}
''';

Future<ProcessResult> _text(Directory d, List<String> extra) {
  void schreib(String n, String s) => File('${d.path}/$n').writeAsStringSync(s);
  schreib('alt.lock', _altLock);
  schreib('neu.lock', _neuLock);
  schreib('outdated.json', _outdated);
  schreib('deps.json', _deps);
  schreib('pubspec.yaml', 'name: app\n');
  return Process.run('python3', <String>[
    '$_wurzel/.github/scripts/deps_pr_text.py',
    '--alt',
    '${d.path}/alt.lock',
    '--neu',
    '${d.path}/neu.lock',
    '--outdated',
    '${d.path}/outdated.json',
    '--deps',
    '${d.path}/deps.json',
    '--pubspec',
    '${d.path}/pubspec.yaml',
    '--lauf',
    'https://example.org/runs/1',
    ...extra,
  ]);
}

String _datei(String pfad) => File('$_wurzel/$pfad')
    .readAsLinesSync()
    .where((String z) => !z.trimLeft().startsWith('#'))
    .join('\n');

/// Die Jobs des Ablaufs: Name → Text (zwei Leerzeichen eingerückt unter jobs:).
Map<String, String> _jobs() {
  final String ganz = _datei('.github/workflows/deps-update.yml');
  final String teil = ganz.substring(ganz.indexOf('\njobs:\n'));
  final Map<String, String> jobs = <String, String>{};
  String? name;
  final StringBuffer b = StringBuffer();
  for (final String z in teil.split('\n')) {
    final Match? m = RegExp(r'^  ([a-z]+):$').firstMatch(z);
    if (m != null) {
      if (name != null) jobs[name] = b.toString();
      name = m.group(1);
      b.clear();
    }
    b.writeln(z);
  }
  if (name != null) jobs[name] = b.toString();
  return jobs;
}

/// Die Schritte eines Jobs.
List<String> _schritte(String job) {
  final List<String> s = <String>[];
  StringBuffer? b;
  for (final String z in job.split('\n')) {
    if (RegExp(r'^      - (name|uses|id):').hasMatch(z)) {
      if (b != null) s.add(b.toString());
      b = StringBuffer();
    }
    b?.writeln(z);
  }
  if (b != null) s.add(b.toString());
  return s;
}

String _schritt(String job, String name) {
  final String s = _schritte(job)
      .firstWhere((String t) => t.contains(name), orElse: () => '');
  expect(s, isNotEmpty, reason: 'Schritt „$name" fehlt');
  return s;
}

void main() {
  late Directory d;
  setUp(() => d = Directory.systemTemp.createTempSync('deps_update_'));
  tearDown(() => d.deleteSync(recursive: true));

  group('PR-Text', () {
    test('Tabelle, Prüfungen mit Links, Geräteprobe', () async {
      final ProcessResult r = await _text(d, <String>[
        '--pruefung',
        'Android: build-android.yml — [Lauf](https://example.org/runs/7)',
        '--pruefung',
        'Linux: build-linux-flatpak.yml',
      ]);
      expect(r.exitCode, 0, reason: '${r.stdout}\n${r.stderr}');
      final String t = r.stdout as String;
      expect(t, contains('## Angehoben (3)'));
      expect(t, contains('| 1.6.2+hotfix.2 | 1.6.2+hotfix.3 | direkt |'));
      expect(t, contains('| `js` | 0.7.2 | — | entfällt |'));
      expect(
          t,
          contains(
              '- ✅ Android: build-android.yml — [Lauf](https://example.org/runs/7)'));
      expect(t, contains('- ✅ Linux: build-linux-flatpak.yml'));
      expect(t, isNot(contains('iOS, macOS, Windows')),
          reason: 'mit --pruefung gelten nur die übergebenen Zeilen');
      expect(t, contains('Anruf führen, auch mit dem Systemfenster'));
      expect(t, contains('`fix(deps): …`'));
      expect(t, contains('- file_picker 10.3.10 → 11.0.3'));
      expect(t,
          contains('- qr 3.0.2 (4.0.0 verfügbar) — eingebunden von: barcode'));
      expect(t, isNot(contains('dartcv4')));
    });

    test('rote Prüfung: Meldung ohne Häkchen', () async {
      final ProcessResult r = await _text(
          d, <String>['--gescheitert', 'build-extras-platforms.yml']);
      expect(r.exitCode, 0, reason: '${r.stdout}\n${r.stderr}');
      final String t = r.stdout as String;
      expect(
          t,
          startsWith(
              '## Anhebung zurückgehalten: **build-extras-platforms.yml** war rot'));
      expect(t, contains('der Prüfzweig ist wieder gelöscht'));
      expect(t, isNot(contains('✅')));
    });
  });

  group('linux-systembibliotheken.sh', () {
    Future<List<String>> lauf(String bundle) async {
      final ProcessResult r = await Process.run('bash', <String>[
        '$_wurzel/.github/scripts/linux-systembibliotheken.sh',
        bundle,
      ]);
      expect(r.exitCode, 0, reason: '${r.stdout}\n${r.stderr}');
      return (r.stdout as String).trim().split('\n');
    }

    test('liest auch ein Bundle ohne x-Bit (so kommt es aus dem Artefakt)',
        () async {
      final Directory b = Directory('${d.path}/bundle/lib')
        ..createSync(recursive: true);
      File('/usr/bin/env').copySync('${d.path}/bundle/app');
      await Process.run('chmod', <String>['-x', '${d.path}/bundle/app']);
      File('${d.path}/bundle/hinweis.txt').writeAsStringSync('kein ELF');

      expect(await lauf('${d.path}/bundle'), contains('libc.so.6'));

      final ProcessResult ldd =
          await Process.run('ldd', <String>['/usr/bin/env']);
      final String libc = RegExp(r'libc\.so\.6 => (\S+)')
          .firstMatch(ldd.stdout as String)!
          .group(1)!;
      File(libc).copySync('${b.path}/libc.so.6.99');
      expect(await lauf('${d.path}/bundle'), isNot(contains('libc.so.6')),
          reason: 'mitgebracht, erkannt am SONAME');
    });
  });

  group('deps-update.yml', () {
    final Map<String, String> j = _jobs();

    test('tests und bauten laufen vor dem Abschluss', () {
      expect(j.keys,
          containsAll(<String>['anheben', 'tests', 'bauten', 'abschluss']));
      expect(j['abschluss'], contains('needs: [anheben, tests, bauten]'));
      expect(j['tests'], contains('flutter test'));
      for (final String job in <String>['anheben', 'tests', 'bauten']) {
        expect(j[job], isNot(contains('continue-on-error')), reason: job);
      }
    });

    test('die drei Release-Abläufe werden gestartet und abgewartet', () {
      final String b = j['bauten']!;
      for (final String wf in <String>[
        'build-android.yml',
        'build-linux-flatpak.yml',
        'build-extras-platforms.yml',
      ]) {
        expect(b, contains(wf));
      }
      expect(b, contains('gh workflow run "\$wf" --ref "\$PRUEFZWEIG"'));
      expect(b, contains('gh run watch "\$id" --exit-status'));
      expect(b, contains('exit \$ROT'),
          reason: 'ein roter Bau muss den Job rot machen');
    });

    test('PR nur, wenn Tests UND Bauten grün waren — und nie im Probelauf', () {
      final String a = j['abschluss']!;
      final String pr = _schritt(a, 'Alles grün');
      expect(pr, contains("needs.tests.result == 'success'"));
      expect(pr, contains("needs.bauten.result == 'success'"));
      expect(pr, contains("env.PROBE != 'true'"));
      expect(
          pr, contains(r'git push -q --force origin "$SHA:refs/heads/$ZWEIG"'));
      expect(pr, contains('gh pr create'));

      final String rot = _schritt(a, 'Etwas war rot');
      expect(rot, isNot(contains('git push')));
      expect(rot, isNot(contains('gh pr')));
      final int probe = rot.indexOf(r'if [ "$PROBE" = "true" ]');
      expect(probe, isNot(-1));
      expect(probe, lessThan(rot.indexOf('gh issue')),
          reason: 'im Probelauf darf nichts im Issue landen');

      expect(_schritt(a, 'Prüfzweig löschen'), contains('if: always()'));
      // deps/automatisch wird nur an EINER Stelle geschoben.
      final String alles = j.values.join();
      expect(RegExp(r'refs/heads/\$ZWEIG').allMatches(alles).length, 1);
    });
  });

  group('Bau-Abläufe und Dependabot', () {
    test('Tags behalten ihre eine Spur, alles andere bekommt eine eigene', () {
      const Map<String, String> spuren = <String, String>{
        'build-android.yml': 'mitglieder-android',
        'build-linux-flatpak.yml': 'mitglieder-release',
        'build-extras-platforms.yml': 'mitglieder-extras',
      };
      spuren.forEach((String wf, String spur) {
        final String s = _datei('.github/workflows/$wf');
        expect(
            s,
            contains("group: \${{ startsWith(github.ref, 'refs/tags/') && "
                "'$spur' || format('$spur-{0}', github.ref) }}"),
            reason: '$wf: ein Probebau darf keinen Release-Bau abbrechen');
      });
    });

    test('Dependabot hebt keine pub-Pakete mehr an', () {
      final String s = _datei('.github/dependabot.yml');
      expect(s, contains('package-ecosystem: "github-actions"'));
      expect(s, isNot(contains('package-ecosystem: "pub"')));
    });
  });
}
